site_name: OSDi Tutorial
site_url: https://ontologies-ull.github.io/OSDi/tutorial/
repo_url: https://github.com/ontologies-ULL/OSDi
repo_name: ontologies-ULL/OSDi

# Content is in docs-src
docs_dir: docs-src

# MkDocs will generate HTML inside docs/tutorial
site_dir: docs/tutorial

plugins:
  - macros
  
theme:
  name: material

extra:
  version: "1.0"
  osdi: "https://w3id.org/ontologies-ULL/OSDi/1.0"

nav:
  - Home: index.md
  - 1. Some tips before starting: before_start.md
  - 2. Explanation of the reference case: reference_case.md
  - 3. Disease modeling:
      - Disease: disease.md
      - Progression: progression.md
  - 4. Parameters: parameter.md
  - 5. Characterizing the risk using pathways: pathway.md
  - 6. Population affected: population.md
#  - Model inputs:
#      - Population: population.md
#      - Epidemiological parameters: epidemiology.md
#      - Interventions & effects: interventions.md
#      - Utilities: utilities.md
  - Decision model:
      - Model structure: model_structure.md
      #- Full worked example (BD): full_example_bd.md
  - Ontology reference (Widoco): https://w3id.org/ontologies-ULL/OSDi
